# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "srvweb01" do |srvweb01|
    srvweb01.vm.box = "bento/ubuntu-26.04"
    srvweb01.vm.network "public_network"
    srvweb01.vm.provider "virtualbox" do |vbox_config|
      vbox_config.name = "servidorWebUbuntu"
      vbox_config.memory = 1024
      vbox_config.cpus    = 1
    end
  end
  config.vm.define "srvweb02" do |srvweb02|
    srvweb02.vm.box = "bento/almalinux-10"
    srvweb02.vm.network "public_network"
    srvweb02.vm.provider "virtualbox" do |vbox_config|
      vbox_config.name = "servidorWebAlmaLinux"
      vbox_config.memory = 512
      vbox_config.cpus    = 1
    end
  end
end
