- name: Playbook para transferir arquivo
  hosts: servidoreslinux
  tasks:

   - name: Tranferir chave pública
     become: true
     ansible.builtin.copy:
      src: /vagrant/key.pub
      dest: /tmp
      mode: preserve
