- name: Instalando pacotes
  hosts: servidoresweb
  tasks:
    - name: Instalando apenas se forem servidores Ubuntu
      become: true
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
        update_cache: 'yes'
      loop:
        - mc
        - nginx
        - nodejs
        - npm
