 # Playbook ambiente react

 - name: Instalando pacotes
   hosts: servidoresweb
   tasks:
     - name: Instalando nos servidores Ubuntu
       become: true
       apt:
         name: "{{ item }}"
         state: present
         update_cache: yes 
       loop:
         - mc
         - nginx
         - nodejs
         - npm
       when: ansible_distribution == "Ubuntu"

 - name: Clonando repositorio
   hosts: ubuntu
   tasks:
     - name: Clona repositorio com exemplo
       git:
         repo: https://github.com/arnab-datta/counter-app.git
         dest: /home/vagrant/counter-app
         clone: yes
         update: yes   

 - name: Executa o build do react no servidor
   hosts: ubuntu
   tasks:
     - name: Builda o projeto
       shell: |
         cd counter-app
         sudo apt upgrade -y
         npm install
         npm run build
         sudo mkdir /var/www/html/counter-app
         sudo cp -r build/. /var/www/html/counter-app/

 - name: Reiniciando serviços
   hosts: ubuntu
   tasks:
     - name: Reiniciando nginx
       become: true
       service:
         name: nginx
         state: started
         enabled: yes
