# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "ansible"   => {"memory" => "512", "cpu" => "2", "ip" => "30", "image" => "ubuntu/jammy64"},
  "srvweb01" => {"memory" => "512",  "cpu" => "1", "ip" => "31", "image" => "ubuntu/jammy64"},
  "srvweb02" => {"memory" => "512",  "cpu" => "1", "ip" => "32", "image" => "debian/bullseye64"},
  "srvbd" => {"memory" => "512",  "cpu" => "1", "ip" => "33", "image" => "centos/7"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.abc.com"
      machine.vm.network "public_network"
      machine.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/iac"]
      end
    config.vm.provision "shell", inline: <<-EOF
      HOSTS=$(head -n7 /etc/hosts)
      echo -e "$HOSTS" > /etc/hosts
      echo '192.168.56.30 ansible.abc.com' >> /etc/hosts
      echo '192.168.56.31 srvweb01.abc.com' >> /etc/hosts
      echo '192.168.56.32 srvweb02.abc.com' >> /etc/hosts
      echo '192.168.56.33 srvbd.abc.com' >> /etc/hosts
      EOF
    end
  end
end