# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "ansible"   => {"memory" => "512", "cpu" => "2", "ip" => "30", "image" => "ubuntu/jammy64", "script" => "/vagrant/script1.sh"},
  "srvweb01" => {"memory" => "512",  "cpu" => "1", "ip" => "31", "image" => "ubuntu/jammy64", "script" => "/vagrant/script2.sh"},
  "srvweb02" => {"memory" => "512",  "cpu" => "1", "ip" => "32", "image" => "debian/bullseye64", "script" => "/vagrant/script2.sh"},
  "srvbd" => {"memory" => "512",  "cpu" => "1", "ip" => "33", "image" => "centos/7", "script" => "/vagrant/script2.sh"}
}

$default_network_interface = `ip route | awk '/^default/ {printf "%s", $5; exit 0}'`

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.abc.com"
      machine.vm.network "public_network", bridge: "#$default_network_interface"
      machine.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/iac"]
      end  
      machine.vm.provision "shell", inline: <<-EOF
        bash #{conf["script"]}
      EOF
    end
  end
end

