$script = <<-EOF
export DEBIAN_FRONTEND=noninteractive
echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

sudo apt update
sudo apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
sudo apt-get install -y ca-certificates curl

# Configuração do repositório oficial do Docker
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"${UBUNTU_CODENAME:-$VERSION_CODENAME}\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

# Instalação do Docker e pacotes extras
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin mc golang-go nodejs mtr
sudo ln -sf /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose

# Inicialização do serviço Docker e permissões
sudo systemctl enable docker
sudo systemctl start docker
sudo systemctl status docker --no-pager
sudo usermod -aG docker vagrant
EOF

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-26.04"
  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.56.200"
  config.vm.provision "shell", inline: $script
  config.vm.provider "virtualbox" do |vbox_config|
    vbox_config.name = "dockerOnUbuntu"
    vbox_config.memory = 1024
    vbox_config.cpus    = 2
  end
end