services:
  app:
    image: eltontorres/meunodeapp:2.0
    ports:
      - 3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    depends_on:
      - mysql  
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

  loadbalancer:
    image: eltontorres/loadbalancer:3.0
    ports:
      - 80:80
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - app
      - mysql

volumes:
  todo-mysql-data:

networks:
  frontend:
  backend:
