# -*- mode: ruby -*-
# vi: set ft=ruby  :

$docker = <<-EOF
sudo apt update
sudo apt upgrade -y
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo apt update
sudo apt-cache policy docker-ce
sudo apt install -y docker-ce docker-compose mc
sudo systemctl enable docker
sudo systemctl start docker
sudo systemctl status docker
sudo usermod -aG docker vagrant     
EOF

$master = <<-EOF
sudo docker swarm init --advertise-addr=192.168.56.100
sudo docker swarm join-token worker | grep docker > /vagrant/worker.sh    
EOF

machines = {
  "master" => {"memory" => "1024", "cpu" => "2", "ip" => "100", "image" => "ubuntu/focal64"},
  "node01" => {"memory" => "1024", "cpu" => "2", "ip" => "101", "image" => "ubuntu/focal64"},
  "node02" => {"memory" => "1024", "cpu" => "2", "ip" => "102", "image" => "ubuntu/focal64"}
}

Vagrant.configure("2") do |config|

  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.abc.dev"
      machine.vm.network "private_network", ip: "192.168.56.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/Docker-Lab"]
      end
      machine.vm.provision "shell", inline: $docker
      if "#{name}" == "master"
        machine.vm.provision "shell", inline: $master
      else
        machine.vm.provision "shell", path: "worker.sh"
      end
    end
  end
end