# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-26.04"
  config.vm.network "public_network"
  config.vm.network "private_network", ip: "192.168.56.123"
  config.vm.synced_folder "/usr", "/vagrant_data"
  config.vm.provider "virtualbox" do |vbox_config|
    vbox_config.name = "servidorUbuntu"
    vbox_config.memory = 1024
    vbox_config.cpus    = 2
  end
end
