FROM nginx:stable-alpine3.17-slim
RUN apk update && apk add git
RUN rm -rf /usr/share/nginx/html/*
RUN git clone https://github.com/elton-bt/simple-abc-site /usr/share/nginx/html
EXPOSE 80
CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
